version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5001:5001
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: points_pal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres